### ISSUE TITLE
Switch to double?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libccd-feedstock#4]
### Comment:

In Debian and Homebrew, the `libccd` package is compiled using `double` as a data type, see https://salsa.debian.org/science-team/libccd/-/blob/0248b4067ab931453ac5be70716f3b74b8047181/debian/rules#L10 and https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libccd.rb#L22 .

For this reason, some downstream libraries assume that CCD is compiled using `double` as a data type, see for example https://github.com/conda-forge/staged-recipes/pull/19049#issuecomment-1139782049 . As the only libraries that depend on libccd are fcl and dart, to avoid that users obtain less precise results with conda-forge packages w.r.t. people that are using apt or homebrew packages and to support mujoco, I think it make sense to switch ccd to use double. 

However, clearly the two ABIs not definitely not compatible. A possible idea is to change the name of the package (for example we could call it `libccd-double`, so that if somebody is really interested in the future we could have a `libccd-float`) to avoid the problem?

**Comment by traversaro** [comment]
fyi @conda-forge/libccd (that I just saw is only @wolfv)

**Comment by wolfv** [comment]
Sounds good to me. Too bad that we didn't do this from the beginning but renaming is probably the best course of action

**Comment by traversaro** [comment]
Migration completed:
* https://github.com/conda-forge/libccd-feedstock/pull/5
* https://github.com/conda-forge/fcl-feedstock/pull/12
* https://github.com/conda-forge/dartsim-feedstock/pull/30
* https://github.com/conda-forge/gazebo-feedstock/pull/137
